# pip install pygments mkdocs-material pymdown-extensions
site_name: META-GP
site_author: Eike Steinig
site_description: Metagenomic diagnostics for accredited pathogen detection and reporting.
copyright: "Copyright © 2023-2025 Eike Steinig. All rights reserved."

site_url: https://meta-gp.github.io/
repo_url: https://github.com/meta-gp/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/mgp-small-logo.png
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  features:
    - navigation.tabs
    - navigation.tabs.sticky


nav:
  - 'META-GP':
    - 'Introduction': 'meta-gp/index.md'
    - 'Quick Start': 'meta-gp/quick-start.md'
    - 'Installation': 'meta-gp/installation.md'
    - 'Basic Usage': 'meta-gp/usage-basic.md'
    - 'Tutorial': 'meta-gp/tutorial.md'
    - 'Workflows': 'meta-gp/workflows.md'
    - 'Databases': 'meta-gp/databases.md'
    - 'Datasets': 'meta-gp/datasets.md'
    - 'Production': 'meta-gp/production.md'
    - 'Interfaces': 'meta-gp/interfaces.md'
    - 'Reports': 'meta-gp/reports.md'
    - 'Accreditation': 'meta-gp/accreditation.md'
    - 'Acknowledgements': 'meta-gp/acknowledgements.md'
    - 'Changelog': 'meta-gp/changelog.md'
  - 'Syndromes':
    - 'Introduction': 'syndromes/index.md'
    - 'Clinical': 'syndromes/clinical.md'
    - 'Public Health': 'syndromes/public-health.md'
  - 'Tools':
    - 'Introduction': 'tools/index.md'